# Generated by Django 4.2.2 on 2023-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0003_alter_subscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='Имя', max_length=255),
        ),
    ]
