# Generated by Django 4.2.2 on 2023-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0004_subscriber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
